version: '3'
services:
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
